(define (eval exp env)
  (cond ((self-evaluating? exp) exp)
        ((variable? exp) (lookup-variable-value exp env))
        ((quoted? exp) (text-of-quotation exp))
        ((assignment? exp) (eval-assignment exp env))
        ((definition? exp) (eval-definition exp env))
        ((if? exp) (eval-if exp env))
        ((lambda? exp)
         (make-procedure (lambda-parameters exp)
                         (lambda-body exp)
                         env))
        ((begin? exp) 
         (eval-sequence (begin-actions exp) env))
        ((cond? exp) (eval (cond->if exp) env))
        ((unless? exp) (eval-unless exp env))
	((application? exp)
         (apply (eval (operator exp) env)
                (list-of-values (operands exp) env)))
        (else
         (error "Unknown expression type -- EVAL" exp))))


(define (unless? exp) (tagged-list? exp 'unless))
(define (unless-cond exp) (cadr exp))
(define (unless-usual exp) (caddr exp))
(define (unless-except exp) (cadddr exp))

(define (eval-unless exp env)
  (if (true? (eval (unless-cond exp) env))
      (eval (unless-except exp) env)
      (eval (unless-usual exp) env)))
