(load "fixed_point.scm")
;; newtons method
(define dx 0.00000001)
(define (newton-transform g)
  (lambda (x)
    (- x (/ (g x) ((deriv g) x)))))
(define (deriv g)
  (lambda (x)
    (/ (- (g (+ x dx)) (g x))
       dx)))
(define (newtons-method g guess)
  (fixed-point (newton-transform g) guess))
