(define (lexical-address-lookup address env)
  (if (null? env)
      (error "empty environment!")
      (if (= (car address) 0)
	  (let* ((element-in-frame (cadr address))
		 (value (list-ref (cadar env) element-in-frame))) 
	    (if (eq? '*unassigned* value)
		(error "Attempted to look up an unassigned variable!")
		value))
	  (lexical-address-lookup (list (- (car address) 1)
					(cadr address))
				  (cdr env)))))

	      
(define (lexical-address-set! address env val)
  (if (null? env)
      (error "empty environment!")
      (if (= (car address) 0)
	  (let ((element-in-frame (cadr address))) 
	    (define (iter frame n)
	      (if (= n 0)
		  (set-car! frame val)
		  (iter (cdr frame) (- n 1))))
	    (iter (cadar env) element-in-frame))
	  (lexical-address-set! (list (- (car address) 1)
				      (cadr address))
				(cdr env)
				val))))
